version: 2
updates:
  # 更新npm依赖和开发依赖
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily" # 每天更新
      time: "02:00" # 设置更新时间为UTC时间的02:00（可根据需要调整）
    commit-message:
      prefix: "chore" # 可改为"deps"或其它自定义前缀
      prefix-development: "chore(dev)" # 用于开发依赖的提交前缀
    rebase-strategy: "auto" # 自动rebase来解决冲突
